// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package robot;

import robot.commands.*;
import robot.subsystems.*;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import robot.subsystems.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 * This class is where the bulk of the robot should be declared.  Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls).  Instead, the structure of the robot
 * (including subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
// The robot's subsystems
    public final effectsSubSys m_effectsSubSys = new effectsSubSys();
    public final cannonSubSys m_cannonSubSys = new cannonSubSys();
    public final drivetrainSubSys m_drivetrainSubSys = new drivetrainSubSys();

// Joysticks
private final Joystick driverJoystick = new Joystick(0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  
  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  /**
  * The container for the robot.  Contains subsystems, OI devices, and commands.
  */
  private RobotContainer() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Smartdashboard Subsystems


    // SmartDashboard Buttons
    SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
    SmartDashboard.putData("fireCannonCmd", new fireCannonCmd( m_cannonSubSys ));
    SmartDashboard.putData("compressorOnCmd", new compressorOnCmd( m_cannonSubSys ));
    SmartDashboard.putData("compressorOffCmd", new compressorOffCmd( m_cannonSubSys ));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD

    // Configure the button bindings
    configureButtonBindings();

    // Configure default commands
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

    // Configure autonomous sendable chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    // New way to put data on tabbed shuffleboard
    // Shuffleboard.getTab("user tab").add(myChooser);
    //
    //auto = new SendableChooser();
	//auto.addDefault(autoNone, new AutoNone());
	//auto.addObject(autoGearOnLeft, new AutoGearOnLeft());
	//auto.addObject(autoGearOnRight, new AutoGearOnRight());
	//auto.addObject(autoGearOnStraight, new AutoGearStrait());
	//SmartDashboard.putData("Auto modes", auto);

    SmartDashboard.putData("Auto Mode", m_chooser);
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings.  Buttons can be created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
// Create some buttons
final JoystickButton compressorOffBtn = new JoystickButton(driverJoystick, 7);        
compressorOffBtn.whenPressed(new compressorOffCmd( m_cannonSubSys ) ,true);
    SmartDashboard.putData("compressorOffBtn",new compressorOffCmd( m_cannonSubSys ) );

final JoystickButton compressorOnBtn = new JoystickButton(driverJoystick, 8);        
compressorOnBtn.whenPressed(new compressorOnCmd( m_cannonSubSys ) ,true);
    SmartDashboard.putData("compressorOnBtn",new compressorOnCmd( m_cannonSubSys ) );

final JoystickButton fireCannonBtn = new JoystickButton(driverJoystick, 2);        
fireCannonBtn.whileHeld(new fireCannonCmd( m_cannonSubSys ) ,true);
    SmartDashboard.putData("fireCannonBtn",new fireCannonCmd( m_cannonSubSys ) );

final JoystickButton driveByJoystickBtn = new JoystickButton(driverJoystick, 1);        
driveByJoystickBtn.whileHeld(new driveByJoystickCmd( m_drivetrainSubSys ) ,true);
    SmartDashboard.putData("driveByJoystickBtn",new driveByJoystickCmd( m_drivetrainSubSys ) );



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
  }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
public Joystick getdriverJoystick() {
        return driverJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
  */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }
  

}

