// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package robot.subsystems;


//import robot.commands.*;
//import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

//import javax.swing.text.html.HTMLDocument.HTMLReader.IsindexAction;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.PneumaticsModuleType;
import edu.wpi.first.wpilibj.Solenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class payloadSubSys extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private Solenoid intakeValve;
private Compressor compressor;
private WPI_TalonSRX intakeRollerMotor;
private WPI_TalonSRX handoffMotor;
private WPI_TalonSRX conveyorMotor;
private WPI_TalonSRX shooterMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private double handoffSpeed, conveyorSpeed, intakeSpeed, shooterSpeed;
    private boolean isCompressorOn, isIntakeExtended;
    
    /**
    *
    */
    public payloadSubSys() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
intakeValve = new Solenoid(0, PneumaticsModuleType.CTREPCM, 1);
 addChild("intakeValve", intakeValve);
 

compressor = new Compressor(1, PneumaticsModuleType.CTREPCM);
 addChild("compressor",compressor);
 

intakeRollerMotor = new WPI_TalonSRX(5);
 
 

handoffMotor = new WPI_TalonSRX(7);
 
 

conveyorMotor = new WPI_TalonSRX(6);
 
 

shooterMotor = new WPI_TalonSRX(8);
 
 


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        enableCompressor();

        handoffSpeed = 0.0;
        conveyorSpeed = 0.0;
        intakeSpeed = 0.0;
        shooterSpeed = 0.0;

        isCompressorOn = true;
        isIntakeExtended = false;
    
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        
        // Motor setting
        handoffMotor.set(handoffSpeed);
        conveyorMotor.set(conveyorSpeed);
        intakeRollerMotor.set(intakeSpeed);
        shooterMotor.set(shooterSpeed);

        // valve and pneumatic setting
        if (isCompressorOn) { compressor.enableDigital(); } else { compressor.disable(); }
        if (isIntakeExtended) { intakeValve.set(true); } else { intakeValve.set(false); }
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void handoffMotorStop(){ handoffSpeed = 0.0; }
    public void handoffMotorStart(double speed){ handoffSpeed = speed; }

    public void conveyorMotorStop(){ conveyorSpeed = 0.0; }
    public void conveyorMotorStart(double speed){ conveyorSpeed = speed; }

    public void intakeRollerMotorStop(){ intakeSpeed = 0.0; }
    public void intakeRollerMotorStart(double speed){ intakeSpeed = -speed; }

    public void shooterMotorStop(){ shooterSpeed = 0.0; }
    public void shooterMotorStart(double speed){ shooterSpeed = speed; }

    public void enableCompressor(){ isCompressorOn = true; }
    public void disableCompressor(){ isCompressorOn = false; }
    public void toggleCompressor() {
        if ( isCompressorOn == true) {
            // turn off Compressor
            isCompressorOn = false;
        } else {
            // turn on Compressor
            isCompressorOn = true;
        }
    }

    public void intakeExtend(){ isIntakeExtended = true; }
    public void intakeRetract(){ isIntakeExtended = false; }

    public boolean isIntakeExtended() {
        return isIntakeExtended;
    }
}

